# docker-compose-redis.yml
# https://developer.confluent.io/confluent-tutorials/kafka-on-docker/#the-docker-compose-file
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:


#💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖
#💖  docker compose -f docker-compose-redis.yml up -d
#💖 docker run -d -p 6379:6379 --name redis redis:7

#💖 Redis CLI로 바로 확인 >>
#💖 > docker exec -it redis redis-cli
#💖 > KEYS *
#💖 > KEYS discodeit:*    //cause. .prefixCacheNameWith("discodeit:")

