server:
  port: 4444

logging:
  level:
    root: info
    org.springframework.retry: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: discodeit
#
## ===============================
## Actuator 설정
## ===============================

# ===============================
# Actuator Info 메타데이터
# ===============================
info:
  app:
    name: discodeit
    version: 1.7.0
  java:
    version: 17
  spring:
    boot:
      version: 3.4.0

  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}

jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET:your-access-token-secret-key-here-make-it-long-and-random}
    expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:600000} # 10 minutes
  refresh-token:
    secret: ${JWT_REFRESH_SECRET:your-refresh-token-secret-key-here-make-it-different-and-long}
    expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 days

  storage:
    type: ${storage.type}
    path: ${storage.path}

  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}


security:
  remember-me:
    key: ${REMEMBER_ME_KEY:test-RememberMeKey}

login:
  account:
    user-admin: ${ACCOUNT_ADMIN:admin123}
    user-admin-password: ${ACCOUNT_ADMIN_PASSWORD:admin123}
    user-admin-email: ${ACCOUNT_ADMIN_EMAIL:admin123@email.com}
    user-default: ${ACCOUNT_DEFAULT:user1}
    user-default-password: ${ACCOUNT_DEFAULT_PASSWORD:user1}
    user-default-email: ${ACCOUNT_DEFAULT_EMAIL:user1@email.com}