spring:
  application:
    name : discodeit
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:discodeitdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  boot:
    admin:
      client:
        url: http://localhost:9090

  security:
    user:
      name: user

discodeit:
  repository:
    type: file
    file-directory: .discodeit
  storage:
    type: ${STORAGE_TYPE:s3}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:/storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

server:
  port: ${PORT:8080}
  servlet:
    session:
      tracking-modes: cookie,url
      timeout: 30m
      cookie:
        http-only: true
        secure: false
        same-site: lax

springdoc:
  swagger-ui:
    path: /api-docs.html
    display-request-duration: true
    enabled: true
  api-docs:
    path: /api-docs
logging:
  level:
    root: INFO
    org.hibernate.SQL: info
    com.sprint.mission.discodeit: info

rememberme:
  key: rememberMeKey