spring:
  application:
    name: discodeit

  profiles:
    active: dev # 기본 dev로 실행되게 설정 (운영 배포시 prod)로 변경

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 100
    properties: # SQL 로그 관련 설정 값
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

discodeit:
  storage:
    type: local
    local:
      root-path: C:/Users/user/Workspace/codeit-sprint-bootcamp/7-sprint-mission/image

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

