spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  level:
    root: warn
    com.sprint.mission.discodeit: info
    org.hibernate.sql: warn
  file:
    path: ./logs

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/discodeit