server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:discodeit;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    user:
      name: user

discodeit:
  storage:
    type: local
    local:
      root-path: "${user.home}/Desktop/DiscodeitUpload_dev"

# Logging
logging:
  level:
    org.springframework.security: TRACE
    com.discodeit.security: TRACE
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE