spring:
  application:
    name : discodeit
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  boot:
    admin:
      client:
        url: ${SPRINT_BOOT_ADMIN_CLIENT_URL}

discodeit:
  repository:
    type: file
    file-directory: .discodeit
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:/storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
server:
  port: ${PORT:8081}
  address: 0.0.0.0

springdoc:
  swagger-ui:
    path: /api-docs.html
    display-request-duration: true
    enabled: true
  api-docs:
    path: /api-docs
logging:
  level:
    root: INFO
    org.hibernate.SQL: info
    com.sprint.mission.discodeit: info
