spring:
  application:
    name : discodeit
discodeit:
  repository:
    type: file
    file-directory:  "${user.home}/Documents/discodeit/data"
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api-docs.html
    display-request-duration: true
  api-docs:
    path: /api-docs

