# Data directory name
data.directory=data

# Data file names
data.path.users=users.json
data.path.channels=channels.json
data.path.participations=participations.json
data.path.channel_messages=channel_messages.json
data.path.direct_messages=direct_messages.json

