spring:
  application:
    name: discodeit

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    open-in-view: false

logging:
  level:
    root: INFO

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers

  endpoint:
    info:
      enabled: true

  info:
    defaults:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0
  datasource:
    url: ${spring.datasource.url:}
    driver-class-name: ${spring.datasource.driver-class-name:}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto:}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}
