spring:
  application:
    name: discodeit

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    open-in-view: false

logging:
  level:
    root: INFO

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage
