server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://prod-db:5432/discodeit
    username: discodeit_user
    password: discodeit_prod_pw

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public

logging:
  level:

    root: INFO
