spring:
  application:
    name: discodeit

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    open-in-view: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    org.springframework.dao: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    root: INFO

discodeit:
  storage:
    type: ${STORAGE_TYPE:local}

    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}

    s3:
      access-key: ${AWS_S3_ACCESS_KEY:}
      secret-key: ${AWS_S3_SECRET_KEY:}
      region: ${AWS_S3_REGION:ap-northeast-2}
      bucket: ${AWS_S3_BUCKET:}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

jwt:
  secret: ${JWT_SECRET:PLEASE_CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_32BYTES_OR_MORE}
  issuer: ${JWT_ISSUER:discodeit}
  access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:900}
  refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:604800}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
    annotations:
      enabled: true

  endpoint:
    info:
      enabled: true

  info:
    defaults:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0
  datasource:
    url: ${spring.datasource.url:}
    driver-class-name: ${spring.datasource.driver-class-name:}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto:}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}