logging:
  level:
    root: debug
server:
  port: 8090
discodeit:
  storage:
    type: local
    local:
      root-path: C:\Users\hyo37\Documents\7-sprint-mission\discordit
      file-path: ${discodeit.storage.local.root-path}\storage\file

spring:
    url: jdbc:postgresql://localhost:8080/discodeit_dev
    username: discodeit_dev
    password: discodeit1234