spring:
  application:
    name: discordit
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret:
    key: ${JWT_SECRET}
    access-token-expiration: 3600000 # 1시간
    refresh-token-expiration: 900000 # 15분
    issuer: discodeit
  maximum-active-count: 10


validation:
  user:
    id:
      min-length: 4
      max-length: 10
    password:
      min-length: 6
      max-length: 12
    display-name:
      min-length: 3
      max-length: 10
    email-regex: "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$"
management:
  observations:
    annotations:
      enabled: true
logging:
  level:
    root: info
  logback:
    rollingpolicy:
admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
  email: ${ADMIN_EMAIL}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
    presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION} # (기본값: 10분)
